drop table happy;
drop table sad;

create table happy(hword varchar(50));
create table sad(sword varchar(50));

insert into happy values('cheerful');
insert into happy values('contented');
insert into happy values('delighted');
insert into happy values('ecstatic');
insert into happy values('elated');
insert into happy values('glad');
insert into happy values('joyful');
insert into happy values('joyous');
insert into happy values('jubilant');
insert into happy values('lively');
insert into happy values('merry');
insert into happy values('overjoyed');
insert into happy values('peaceful');
insert into happy values('pleasant');
insert into happy values('pleased');
insert into happy values('thrilled');
insert into happy values('thrilled');
insert into happy values('upbeat');
insert into happy values('blessed');
insert into happy values('blest');
insert into happy values('blissful');
insert into happy values('blithe');
insert into happy values('captivated');
insert into happy values('chipper');
insert into happy values('chirpy');
insert into happy values('content');
insert into happy values('convivial');
insert into happy values('exultant');
insert into happy values('flying high');
insert into happy values('gay');
insert into happy values('gleeful');
insert into happy values('gratified');
insert into happy values('intoxicated');
insert into happy values('jolly');
insert into happy values('laughing');
insert into happy values('light');
insert into happy values('looking good');
insert into happy values('mirthful');
insert into happy values('on cloud nine');
insert into happy values('peppy');
insert into happy values('perky');
insert into happy values('playful');
insert into happy values('sunny');
insert into happy values('sparkling');
insert into happy values('tickled');
insert into happy values('tickled pink');
insert into happy values('up');
insert into happy values('walking on air');
insert into happy values('happy');


insert into sad values('bitters');
insert into sad values('dismal');
insert into sad values('heartbroken');
insert into sad values('melancholy');
insert into sad values('mournful');
insert into sad values('pessimistic');
insert into sad values('somber');
insert into sad values('sorrowful');
insert into sad values('sorry');
insert into sad values('wistful');
insert into sad values('bereaved');
insert into sad values('blue');
insert into sad values('cheerless');
insert into sad values('dejected');
insert into sad values('despairing');
insert into sad values('despondent');
insert into sad values('disconsolate');
insert into sad values('distressed');
insert into sad values('doleful');
insert into sad values('down');
insert into sad values('down in dumps');
insert into sad values('down in mouth');
insert into sad values('downcast');
insert into sad values('forlorn');
insert into sad values('gloomy');
insert into sad values('glum');
insert into sad values('grief-stricken');
insert into sad values('grievedst');
insert into sad values('heartsick');
insert into sad values('heavyhearted');
insert into sad values('hurting');
insert into sad values('in doldrums');
insert into sad values('in grief');
insert into sad values('in the dumps');
insert into sad values('languishing');
insert into sad values('low-spirited');
insert into sad values('low');
insert into sad values('lugubrious');
insert into sad values('morbid');
insert into sad values('morose');
insert into sad values('out of sorts');
insert into sad values('pensive');
insert into sad values('sick at heart');
insert into sad values('troubled');
insert into sad values('weeping');
insert into sad values('woebegone');
insert into sad values('sad');